spring:
  application:
    name: order-service-test
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    hibernate:
      ddl-auto: 'create-drop'
  cloud:
    discovery:
      enabled: false
  sql:
    init:
      platform: h2
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
eureka:
  client:
    enabled: false
